name: vealth
description: AI-driven horse teeth age analysis app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  
  # Camera & Image Processing
  image_picker: ^1.1.2
  camera: ^0.11.0+1
  
  # Storage & File Management
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  
  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # HTTP & Authentication
  http: ^1.2.1
  crypto: ^3.0.3
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
